### ISSUE TITLE
plot failed. 

### ISSUE THREAD

**Issue by jyzhong** [uzh-rpg/rpg_trajectory_evaluation#1]
@zhangzichao 
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'serif'] not found. Falling back to DejaVu Sans
....
OSError: [Errno 2] No such file or directory: 'latex'

hope get your advice.

**Comment by zhangzichao** [comment]
Hi, do you have latex installed on your OS? By default, it uses latex for plotting.

You can also try setting using latex to false (at the beginning of the script you execute) by changing

```python
rc('text', usetex=True)
```
to
```python
rc('text', usetex=False)
```

**Comment by jyzhong** [comment]
@zhangzichao  thanks for your reply. After install  latex, problem solved!
