### ISSUE TITLE
Unexpected relative error.

### ISSUE THREAD

**Issue by JJQ7** [uzh-rpg/rpg_trajectory_evaluation#16]
Hi, Thanks for providing this useful tool. But something wrong happened. I evaluate the VINS-Mono on this tool. The alignment is correct, while the translation errors seem to be larger than the result showed in the aligned trajectory.
Could anyone offer some advices?  Great Thanks!

**Comment by JJQ7** [comment]
![image](https://user-images.githubusercontent.com/21231214/57175800-a5ebab00-6e82-11e9-94a5-417c92d310d5.png)
![image](https://user-images.githubusercontent.com/21231214/57175819-c0258900-6e82-11e9-985d-8decfad70c31.png)
![image](https://user-images.githubusercontent.com/21231214/57175835-e814ec80-6e82-11e9-939b-c69b394c88a9.png)
![image](https://user-images.githubusercontent.com/21231214/57175839-f105be00-6e82-11e9-8d31-1c1194cfeef2.png)

**Comment by sjoaij** [comment]
I meet same question

**Comment by sjoaij** [comment]
@zhangzichao

**Comment by kminoda** [comment]
I also faced the same problem. Did you get to solve this? @JJQ7

**Comment by JJQ7** [comment]
> I also faced the same problem. Did you get to solve this? @JJQ7

Euroc dataset provides two ground-truth trajectories. a)  the inertial coordinate frame. b) the camera coordinate frame.  Most of the algorithms estimate the trajectory of IMU (a).
If using (b), the problem may occur.
