### ISSUE TITLE
How to build this tool? OF COURSE, I HAVE READ README. BUT I NEED MORE DETAILS.

### ISSUE THREAD

**Issue by IvyGabriel** [uzh-rpg/rpg_trajectory_evaluation#27]
Hi,
I want to use this trajectory evaluation tool. Need someone's guidances, i have installed all dependencies and git clone "catkin_simple" what you mentioned. Then i catkin_make src of "catkin_simple", git clone "rpg_trajectory_evaluation", cd rpg_trajectory_evaluation. BUT WHEN I INPUT COMMAND"catkin_simple", IT SAYS "command no found". SO WHAT'S NEXT STEP or COMMAND? WHAT should i do?
THANK YOU!!!

**Comment by nkhedekar** [comment]
The command you are looking for is `catkin_make`

**Comment by IvyGabriel** [comment]
@nkhedekar THANK YOU SO MUCH!!!
