### ISSUE TITLE
What is the difference between vislam-ba and visual-rp?

### ISSUE THREAD

**Issue by JunsukLee** [uzh-rpg/rpg_trajectory_evaluation#33]
I have a question.
What is the difference between vislam-ba and visual-rp?
If you can answer my questions, I would be very grateful.

**Comment by zhangzichao** [comment]
It is described here https://github.com/uzh-rpg/rpg_trajectory_evaluation#advanced-different-estimation-type They just look for different file names for the trajectory estimation results, and the analysis afterwards is the same.

It is just a convenient way of feed different estimates into the script, if your algorithm output different types of poses (real-time poses after each image is processed, or bundle adjusted poses after the whole sequence is processed).

**Comment by JunsukLee** [comment]
Thank you!!
