### ISSUE TITLE
port over to python3

### ISSUE THREAD

**Issue by snakehaihai** [uzh-rpg/rpg_trajectory_evaluation#57]
Hi 
I really like this package way better than the EVO, but it is less easy to run it anymore due to most of the existing hardware running on ubuntu 20.04 /python3. How complex is it to upgrade to python3?

**Comment by ShendiS** [comment]
you can use the package 2to3 to translate the scripts to python3 , although it is not very complex to upgrade it manually. Just make sure after you have all the packages installed. I just used it and it worked fine !

**Comment by ChanJoon** [comment]
How about using pyenv? It is easy to use various python versions

**Comment by snakehaihai** [comment]
> How about using pyenv? It is easy to use various python versions

this works. thx
