### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by arjunskumar** [uzh-rpg/rpg_trajectory_evaluation#6]
getting index error, attaching my input data

[stamped_groundtruth.txt](https://github.com/uzh-rpg/rpg_trajectory_evaluation/files/2667205/stamped_groundtruth.txt)
[stamped_traj_estimate.txt](https://github.com/uzh-rpg/rpg_trajectory_evaluation/files/2667206/stamped_traj_estimate.txt)

**Comment by arjunskumar** [comment]
@johnjin404: please check your timestamps are same in the two files.

**Comment by johnjin404** [comment]
thank u very much for pointing out the problem, it works!

**Comment by suraj-bijjahalli** [comment]
Hello, Im facing the same issue but in my case, the number of ground truth timestamps (9418) far exceed the number of traj estimate timestamps (1628). Could you please clarify exactly what you did?
I thought the script was supposed to temporally align the two..?

**Comment by SolarSLAM** [comment]
> @johnjin404: please check your timestamps are same in the two files.

hello, I want to know how to make the timestamps same.The timestamp of trajactory estimated is saved by ros , it's different from groundtruth
